In [70]:
import numpy as np
from macholib.ptypes import sizeof
from numpy import dtype

## Data Types and Attributes

In [71]:
a1 = np.array([1, 2, 3])
type(a1)

numpy.ndarray

![](IMG_3155.jpg)

In [72]:
# 2x3
a2 = np.array([[1, 2.0, 3.0],
       [4, 5, 6.5]])

# 3x3x2 n-dimensional array?
a3 = np.array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],
       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [73]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [74]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [75]:
a1.shape

(3,)

In [76]:
a2.shape

(2, 3)

In [77]:
a3.shape

(2, 3, 3)

In [78]:
# show the dimensions of hte n-dim arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [79]:
# Look at the data types dtype
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [80]:
print(a2[1][1])

5.0


In [81]:
# Show Sizes (number of elements in each n-dim array)
a1.size, a2.size, a3.size

(3, 6, 18)

In [82]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a Data Frame (pandas) from a Numpy Array (numpy)

In [83]:
import pandas as pd
df = pd.DataFrame(a2)

In [84]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

In [85]:
df[2][1]

6.5

## Machine Learning is = finding patterns in Numpy Arrays

## Creating Arrays

In [86]:
import numpy as np
sample_array = np.array([1, 2, 3])
print("the type is: ")
type(sample_array)

the type is: 


numpy.ndarray

In [87]:
print("the data type is: ")
sample_array.dtype

the data type is: 


dtype('int32')

In [88]:
# 4x4 array filled with ones
ashape = (4, 4)
ones = np.ones(ashape)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
ones.dtype

dtype('float64')

In [90]:
type(ones)

numpy.ndarray

In [91]:
# 4x4 array filled with zeros
zeros = np.zeros(ashape)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
# Create array from 0 to 100 - noninclusive - and increment value 5 steps...
range_array = np.arange(0, 100, 5, dtype=int)
range_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [93]:
# Random Array with value ranging from 0 to 10 and make it 2-D per (ashape = (4, 4))
random_array = np.random.randint(0, 10, size=ashape)
random_array

array([[9, 5, 7, 5],
       [2, 6, 9, 3],
       [3, 9, 0, 6],
       [2, 3, 1, 8]])

In [94]:
# show size nd shape of hte ransom array
random_array.dtype

dtype('int32')

In [95]:
random_array.shape

(4, 4)

In [96]:
random_array.size

16

In [97]:
# random.random will return random floats between 0 and 1 ... I can multiply them all by 100
randarray = np.random.random((8, 8))
randarray

array([[0.49794007, 0.67941112, 0.65078591, 0.26879524, 0.06732467,
        0.77144514, 0.48098413, 0.32920641],
       [0.51064106, 0.26362883, 0.31051155, 0.62685344, 0.55744981,
        0.31857956, 0.39484322, 0.25797459],
       [0.58224112, 0.16162871, 0.59813382, 0.82582358, 0.15639172,
        0.73430052, 0.40864343, 0.7786879 ],
       [0.80397057, 0.78607144, 0.59228702, 0.6644892 , 0.64656729,
        0.42563648, 0.51356833, 0.50125784],
       [0.03708381, 0.7081161 , 0.6204306 , 0.77780853, 0.45940947,
        0.37980555, 0.2918922 , 0.55722886],
       [0.0841636 , 0.63128167, 0.94457049, 0.89123753, 0.87858258,
        0.34475163, 0.70310053, 0.5273376 ],
       [0.65931696, 0.26829063, 0.60776708, 0.04815737, 0.69550064,
        0.29927188, 0.16563555, 0.33225194],
       [0.16543775, 0.91463798, 0.28402501, 0.10760726, 0.11700177,
        0.7555236 , 0.83889446, 0.03553703]])

In [98]:
# Quick way to multiply ALL elements in this 2-D array by a constant (100)
randarray100 = randarray * 100
randarray100

array([[49.79400733, 67.94111176, 65.07859141, 26.87952387,  6.73246669,
        77.14451384, 48.09841323, 32.92064077],
       [51.06410562, 26.36288287, 31.051155  , 62.68534377, 55.74498106,
        31.85795596, 39.48432209, 25.79745859],
       [58.22411233, 16.16287104, 59.81338198, 82.58235773, 15.63917185,
        73.43005193, 40.86434321, 77.86879044],
       [80.39705676, 78.60714435, 59.22870187, 66.44892028, 64.65672868,
        42.5636479 , 51.35683338, 50.12578437],
       [ 3.70838109, 70.81160952, 62.04306002, 77.78085346, 45.94094656,
        37.98055547, 29.18922036, 55.72288625],
       [ 8.41636017, 63.12816691, 94.45704879, 89.12375349, 87.85825798,
        34.4751627 , 70.3100532 , 52.73376047],
       [65.93169556, 26.82906337, 60.77670794,  4.815737  , 69.55006394,
        29.92718777, 16.56355549, 33.22519401],
       [16.54377455, 91.4637981 , 28.40250059, 10.76072648, 11.70017702,
        75.55235988, 83.88944582,  3.55370267]])

## Pseudo random numbers are generated ... look into using a seed
seed(seed=None)


Reseed a legacy MT19937 BitGenerator
This is a convenience, legacy function.
The best practice is to not reseed a BitGenerator, rather to recreate a new one. This method is here for legacy reasons. This example demonstrates best practice.
>>> from numpy.random import MT19937
>>> from numpy.random import RandomState, SeedSequence
>>> rs = RandomState(MT19937(SeedSequence(123456789)))
### Later, you want to restart the stream
>>> rs = RandomState(MT19937(SeedSequence(987654321)))

In [99]:
np.random.seed()
randarray100

array([[49.79400733, 67.94111176, 65.07859141, 26.87952387,  6.73246669,
        77.14451384, 48.09841323, 32.92064077],
       [51.06410562, 26.36288287, 31.051155  , 62.68534377, 55.74498106,
        31.85795596, 39.48432209, 25.79745859],
       [58.22411233, 16.16287104, 59.81338198, 82.58235773, 15.63917185,
        73.43005193, 40.86434321, 77.86879044],
       [80.39705676, 78.60714435, 59.22870187, 66.44892028, 64.65672868,
        42.5636479 , 51.35683338, 50.12578437],
       [ 3.70838109, 70.81160952, 62.04306002, 77.78085346, 45.94094656,
        37.98055547, 29.18922036, 55.72288625],
       [ 8.41636017, 63.12816691, 94.45704879, 89.12375349, 87.85825798,
        34.4751627 , 70.3100532 , 52.73376047],
       [65.93169556, 26.82906337, 60.77670794,  4.815737  , 69.55006394,
        29.92718777, 16.56355549, 33.22519401],
       [16.54377455, 91.4637981 , 28.40250059, 10.76072648, 11.70017702,
        75.55235988, 83.88944582,  3.55370267]])

In [100]:
# Pseudo random numbers
np.random.seed(seed=20)
# These all appear as random but if you want reproducible random numbers for the sake of re-creating an issue for instance, you can use a seed()
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4


array([[3, 9, 4],
       [6, 7, 2],
       [0, 6, 8],
       [5, 3, 0],
       [6, 6, 0]])

In [101]:
#finding unique numbers in an array
unique_array = np.unique([1, 2, 3, 4, 5, 1, 1, 2, 2, 44])

In [102]:
# @hen displaying these, it's important to remember that 'unique' is different than 'not a duplicate' ... this takes all numbers and return 1 vale for each, regardless of how many of that particular value are found in the array
unique_array

array([ 1,  2,  3,  4,  5, 44])

In [103]:
# Now try unique with the random array of integers
unique_rand = np.unique(random_array_4)
unique_rand

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
random_array_4

array([[3, 9, 4],
       [6, 7, 2],
       [0, 6, 8],
       [5, 3, 0],
       [6, 6, 0]])

## 3. Viewing Arrays and Matrices

In [105]:
a1

array([1, 2, 3])

In [106]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [110]:
print(a3) # 2x3x3
a3.shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


(2, 3, 3)

In [115]:
print("Get all of the first elements")
print("****")
print(a1[0])
print("****")
print(a2[0])
print("****")
print(a3[0])
print("****")

Get all of the first elements
****
1
****
[1. 2. 3.]
****
[[1 2 3]
 [4 5 6]
 [7 8 9]]
****


In [116]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[9, 5, 7, 5, 2],
         [6, 9, 3, 3, 9],
         [0, 6, 2, 3, 1],
         [8, 0, 2, 7, 6]],

        [[6, 8, 2, 1, 3],
         [2, 6, 9, 4, 6],
         [4, 8, 6, 2, 3],
         [1, 5, 2, 1, 8]],

        [[2, 4, 4, 8, 6],
         [0, 3, 4, 0, 5],
         [6, 9, 7, 4, 0],
         [6, 1, 9, 6, 7]]],


       [[[9, 7, 6, 9, 8],
         [8, 2, 2, 1, 5],
         [2, 9, 7, 5, 5],
         [9, 6, 9, 9, 5]],

        [[2, 9, 6, 1, 8],
         [1, 0, 8, 5, 0],
         [6, 5, 4, 2, 9],
         [9, 4, 5, 3, 9]],

        [[7, 1, 2, 3, 6],
         [5, 4, 4, 1, 8],
         [7, 1, 9, 2, 3],
         [4, 4, 4, 9, 0]]]])

In [117]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [133]:
a4[1][0][2][4]

5

In [122]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [129]:
a3_split = a3[:2, :3, 2:3]

In [130]:
print(a3_split)

[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]]


## Manipulating and Comparing arrays

In [143]:
### Arithmetic
a1

array([1, 2, 3])

In [144]:
ones = np.ones(3)

In [145]:
ones

array([1., 1., 1.])

In [147]:
# adding and subtracting equal sized arrays
result = a1 + ones
result

array([2., 3., 4.])

In [149]:
result = a1 - ones
result

array([0., 1., 2.])

In [153]:
# Look at a2 it is a 2D array with 3 elements, a1 also has 3 elements, so multiplying a1*a2 should take the elements of a1 and multiply them by BOTH roews in a2 (they also have 3 elements)
result = a1*a2
print(a1)
print(a2)
print(result)

[1 2 3]
[[1.  2.  3. ]
 [4.  5.  6.5]]
[[ 1.   4.   9. ]
 [ 4.  10.  19.5]]


In [155]:
# a1 * a3 is possible because the shape is correct
result = a1 * a3
print(a1)
print(a3)
print(result)

[1 2 3]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[[ 1  4  9]
  [ 4 10 18]
  [ 7 16 27]]

 [[10 22 36]
  [13 28 45]
  [16 34 54]]]


In [156]:
# Solving broad casting issues with different shapes of arrays
# think on this problem, maybe reshape() an array
print(a2)
print(a3)

[[1.  2.  3. ]
 [4.  5.  6.5]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [157]:
print(a2.shape)
print(a3.shape)

(2, 3)
(2, 3, 3)


In [165]:
reshaped_array = a2[:, np.newaxis] + a3
reshaped_array

array([[[ 2. ,  4. ,  6. ],
        [ 5. ,  7. ,  9. ],
        [ 8. , 10. , 12. ]],

       [[14. , 16. , 18.5],
        [17. , 19. , 21.5],
        [20. , 22. , 24.5]]])

In [167]:
print("This is a2 normal")
print(a2)
print("This is a2 modified")
a2mod = a2[:, np.newaxis]
print(a2mod)

This is a2 normal
[[1.  2.  3. ]
 [4.  5.  6.5]]
This is a2 modified
[[[1.  2.  3. ]]

 [[4.  5.  6.5]]]


In [169]:
a2.shape

(2, 3)

In [170]:
a3.shape

(2, 3, 3)

In [171]:
a2mod.shape

(2, 1, 3)

### Aggregation
Aggregation = performing the same operation on a number of things

In [176]:
listy_list = [1, 2, 3]
print(listy_list)
print(type(listy_list))


[1, 2, 3]
<class 'list'>


In [182]:
print(a1)
print(listy_list)

[1 2 3]
[1, 2, 3]


In [181]:
sum(listy_list)

6

In [183]:
sum(a1)

np.int64(6)

In [184]:
np.sum(a1)

np.int64(6)

In [186]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [187]:
massive_array[:10]

array([0.81773566, 0.45973847, 0.92241181, 0.04216   , 0.46469294,
       0.98419577, 0.05974547, 0.1934242 , 0.62818961, 0.09752837])

In [188]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

2.91 ms ± 100 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
12.8 µs ± 33.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [190]:
2910/12.8

227.34375

In [191]:
# So the np.sum is 227 times faster than the regular python sum.
# That is why its better to use np.sum on np data and not python sum on np data

In [192]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [203]:
print(np.mean(a2))
print(21.5 / np.size(a2))

3.5833333333333335
3.5833333333333335


In [206]:
# Statistical Operations
# MEAN or AVERAGE
print("The Mean / average is: ")
print(np.mean(a2))

# STANDARD DEVIATION = a measure of how spread out a number is from the mean
# and is the square root of the variant ... so sqrt(np.var(a2))
print("The Standard Deviation is: ")
print(np.std(a2))

# Square root of the variant
print("The sqrt of the variant is: ")
print(np.sqrt(np.var(a2)))

# VARIANCE
# The measure of the average degree to which each number is different to the mean.
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
print("The Variance is: ")
print(np.var(a2))

The Mean / average is: 
3.5833333333333335
The Standard Deviation is: 
1.8352262954621035
The sqrt of the variant is: 
1.8352262954621035
The Variance is: 
3.368055555555556


## Real World Example of calculating Means and Variances and what they are by definition

## Problem Definition:
![](statistics-dogs-graph.gif)

To calculate the variance follow these steps:

Calculate the Mean (the simple average of the numbers)
Then for each number: subtract the Mean and square the result (the squared difference).
Then calculate the average of those squared differences. (Why Square?)

Example
You and your friends have just measured the heights of your dogs (in millimeters):

dogs on graph shoulder heights

The heights (at the shoulders) are: 600 mm, 470 mm, 170 mm, 430 mm and 300 mm.

Find out the Mean, the Variance, and the Standard Deviation.

In [208]:
# Step 1: Calculate the mean
print("The dog heights")
dog_heights = np.array([170, 300, 430, 470, 600])
print(dog_heights)

The dog heights
[170 300 430 470 600]


In [216]:
print("MEAN The dog heights average / mean")
dog_heights_mean = np.mean(dog_heights)
print(dog_heights_mean)

MEAN The dog heights average / mean
394.0


In [217]:
print("Now subtract the mean() from each number")
dog_heights_sub_mean = np.subtract(dog_heights, dog_heights_mean)
print(dog_heights_sub_mean)

Now subtract the mean() from each number
[-224.  -94.   36.   76.  206.]


In [218]:
print("Now square each number in the array")
dog_heights_sub_mean_sqrd = np.square(dog_heights_sub_mean)
print(dog_heights_sub_mean_sqrd)

Now square each number in the array
[50176.  8836.  1296.  5776. 42436.]


In [219]:
print("VARIANCE = Now take the average/mean of the square array [[dog_heights_sub_mean_sqrd]]")
dog_heights_sub_mean_sqrd_mean = np.mean(dog_heights_sub_mean_sqrd)
print(dog_heights_sub_mean_sqrd_mean)

VARIANCE = Now take the average/mean of the square array [[dog_heights_sub_mean_sqrd]]
21704.0


In [220]:
print("STANDARD DEVIATION Now take the sqrt of the Variance (21704)")
standard_dev = np.sqrt(dog_heights_sub_mean_sqrd_mean)
print(standard_dev)

STANDARD DEVIATION Now take the sqrt of the Variance (21704)
147.32277488562318
