In [1]:
import numpy as np
from numpy import dtype

## Data Types and Attributes

In [2]:
a1 = np.array([1, 2, 3])
type(a1)

numpy.ndarray

![](IMG_3155.jpg)

In [3]:
# 2x3
a2 = np.array([[1, 2.0, 3.0],
       [4, 5, 6.5]])

# 3x3x2 n-dimensional array?
a3 = np.array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],
       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [4]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
# show the dimensions of hte n-dim arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
# Look at the data types dtype
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [11]:
print(a2[1][1])

5.0


In [12]:
# Show Sizes (number of elements in each n-dim array)
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a Data Frame (pandas) from a Numpy Array (numpy)

In [14]:
import pandas as pd
df = pd.DataFrame(a2)

In [15]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

In [16]:
df[2][1]

6.5

## Machine Learning is = finding patterns in Numpy Arrays

## Creating Arrays

In [17]:
import numpy as np
sample_array = np.array([1, 2, 3])
print("the type is: ")
type(sample_array)

the type is: 


numpy.ndarray

In [18]:
print("the data type is: ")
sample_array.dtype

the data type is: 


dtype('int32')

In [19]:
# 4x4 array filled with ones
ashape = (4, 4)
ones = np.ones(ashape)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
# 4x4 array filled with zeros
zeros = np.zeros(ashape)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# Create array from 0 to 100 - noninclusive - and increment value 5 steps...
range_array = np.arange(0, 100, 5, dtype=int)
range_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [24]:
# Random Array with value ranging from 0 to 10 and make it 2-D per (ashape = (4, 4))
random_array = np.random.randint(0, 10, size=ashape)
random_array

array([[7, 2, 4, 2],
       [2, 3, 1, 2],
       [2, 2, 3, 2],
       [2, 6, 5, 9]])

In [25]:
# show size nd shape of hte ransom array
random_array.dtype

dtype('int32')

In [26]:
random_array.shape

(4, 4)

In [27]:
random_array.size

16

In [28]:
# random.random will return random floats between 0 and 1 ... I can multiply them all by 100
randarray = np.random.random((8, 8))
randarray

array([[0.55738959, 0.461231  , 0.12685155, 0.77892835, 0.22145226,
        0.58599679, 0.18044235, 0.5494702 ],
       [0.78649683, 0.25711129, 0.34359152, 0.40739734, 0.09680585,
        0.39984367, 0.17942937, 0.7465615 ],
       [0.42926915, 0.15024414, 0.74276193, 0.11136396, 0.15902124,
        0.97302769, 0.16626444, 0.50526823],
       [0.88530564, 0.60242656, 0.8412441 , 0.81148903, 0.17378196,
        0.25834765, 0.09124348, 0.86727722],
       [0.4866519 , 0.41234173, 0.2937803 , 0.69407596, 0.34614874,
        0.05577219, 0.74478687, 0.57153423],
       [0.20396355, 0.82477408, 0.18829671, 0.66918525, 0.77708479,
        0.519547  , 0.5969157 , 0.69850417],
       [0.55092407, 0.72256201, 0.23779944, 0.20299603, 0.05566068,
        0.68236434, 0.97001965, 0.67450247],
       [0.25301309, 0.1314869 , 0.08830362, 0.91460818, 0.18038259,
        0.065758  , 0.30698747, 0.77009603]])

In [29]:
# Quick way to multiply ALL elements in this 2-D array by a constant (100)
randarray100 = randarray * 100
randarray100

array([[55.73895874, 46.12309957, 12.68515457, 77.89283523, 22.14522636,
        58.5996789 , 18.04423502, 54.94701996],
       [78.64968252, 25.7111285 , 34.35915152, 40.73973423,  9.68058482,
        39.98436728, 17.94293681, 74.65614961],
       [42.926915  , 15.02441355, 74.27619316, 11.13639602, 15.90212404,
        97.30276946, 16.62644438, 50.5268226 ],
       [88.53056375, 60.24265644, 84.12440988, 81.14890303, 17.3781958 ,
        25.83476521,  9.12434812, 86.72772233],
       [48.66519045, 41.23417261, 29.37803019, 69.40759641, 34.61487388,
         5.57721916, 74.47868683, 57.15342256],
       [20.39635495, 82.47740841, 18.82967065, 66.91852499, 77.70847949,
        51.95470013, 59.69156958, 69.85041662],
       [55.09240703, 72.25620097, 23.77994435, 20.2996035 ,  5.56606756,
        68.23643405, 97.00196477, 67.45024671],
       [25.30130913, 13.14869041,  8.83036174, 91.46081808, 18.03825906,
         6.57579984, 30.69874691, 77.0096026 ]])

## Pseudo random numbers are generated ... look into using a seed
seed(seed=None)


Reseed a legacy MT19937 BitGenerator
This is a convenience, legacy function.
The best practice is to not reseed a BitGenerator, rather to recreate a new one. This method is here for legacy reasons. This example demonstrates best practice.
>>> from numpy.random import MT19937
>>> from numpy.random import RandomState, SeedSequence
>>> rs = RandomState(MT19937(SeedSequence(123456789)))
### Later, you want to restart the stream
>>> rs = RandomState(MT19937(SeedSequence(987654321)))

In [30]:
np.random.seed()
randarray100

array([[55.73895874, 46.12309957, 12.68515457, 77.89283523, 22.14522636,
        58.5996789 , 18.04423502, 54.94701996],
       [78.64968252, 25.7111285 , 34.35915152, 40.73973423,  9.68058482,
        39.98436728, 17.94293681, 74.65614961],
       [42.926915  , 15.02441355, 74.27619316, 11.13639602, 15.90212404,
        97.30276946, 16.62644438, 50.5268226 ],
       [88.53056375, 60.24265644, 84.12440988, 81.14890303, 17.3781958 ,
        25.83476521,  9.12434812, 86.72772233],
       [48.66519045, 41.23417261, 29.37803019, 69.40759641, 34.61487388,
         5.57721916, 74.47868683, 57.15342256],
       [20.39635495, 82.47740841, 18.82967065, 66.91852499, 77.70847949,
        51.95470013, 59.69156958, 69.85041662],
       [55.09240703, 72.25620097, 23.77994435, 20.2996035 ,  5.56606756,
        68.23643405, 97.00196477, 67.45024671],
       [25.30130913, 13.14869041,  8.83036174, 91.46081808, 18.03825906,
         6.57579984, 30.69874691, 77.0096026 ]])