In [70]:
import numpy as np
from numpy import dtype

## Data Types and Attributes

In [71]:
a1 = np.array([1, 2, 3])
type(a1)

numpy.ndarray

![](IMG_3155.jpg)

In [72]:
# 2x3
a2 = np.array([[1, 2.0, 3.0],
       [4, 5, 6.5]])

# 3x3x2 n-dimensional array?
a3 = np.array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],
       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [73]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [74]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [75]:
a1.shape

(3,)

In [76]:
a2.shape

(2, 3)

In [77]:
a3.shape

(2, 3, 3)

In [78]:
# show the dimensions of hte n-dim arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [79]:
# Look at the data types dtype
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [80]:
print(a2[1][1])

5.0


In [81]:
# Show Sizes (number of elements in each n-dim array)
a1.size, a2.size, a3.size

(3, 6, 18)

In [82]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a Data Frame (pandas) from a Numpy Array (numpy)

In [83]:
import pandas as pd
df = pd.DataFrame(a2)

In [84]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

In [85]:
df[2][1]

6.5

## Machine Learning is = finding patterns in Numpy Arrays

## Creating Arrays

In [86]:
import numpy as np
sample_array = np.array([1, 2, 3])
print("the type is: ")
type(sample_array)

the type is: 


numpy.ndarray

In [87]:
print("the data type is: ")
sample_array.dtype

the data type is: 


dtype('int32')

In [88]:
# 4x4 array filled with ones
ashape = (4, 4)
ones = np.ones(ashape)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
ones.dtype

dtype('float64')

In [90]:
type(ones)

numpy.ndarray

In [91]:
# 4x4 array filled with zeros
zeros = np.zeros(ashape)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
# Create array from 0 to 100 - noninclusive - and increment value 5 steps...
range_array = np.arange(0, 100, 5, dtype=int)
range_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [93]:
# Random Array with value ranging from 0 to 10 and make it 2-D per (ashape = (4, 4))
random_array = np.random.randint(0, 10, size=ashape)
random_array

array([[9, 5, 7, 5],
       [2, 6, 9, 3],
       [3, 9, 0, 6],
       [2, 3, 1, 8]])

In [94]:
# show size nd shape of hte ransom array
random_array.dtype

dtype('int32')

In [95]:
random_array.shape

(4, 4)

In [96]:
random_array.size

16

In [97]:
# random.random will return random floats between 0 and 1 ... I can multiply them all by 100
randarray = np.random.random((8, 8))
randarray

array([[0.49794007, 0.67941112, 0.65078591, 0.26879524, 0.06732467,
        0.77144514, 0.48098413, 0.32920641],
       [0.51064106, 0.26362883, 0.31051155, 0.62685344, 0.55744981,
        0.31857956, 0.39484322, 0.25797459],
       [0.58224112, 0.16162871, 0.59813382, 0.82582358, 0.15639172,
        0.73430052, 0.40864343, 0.7786879 ],
       [0.80397057, 0.78607144, 0.59228702, 0.6644892 , 0.64656729,
        0.42563648, 0.51356833, 0.50125784],
       [0.03708381, 0.7081161 , 0.6204306 , 0.77780853, 0.45940947,
        0.37980555, 0.2918922 , 0.55722886],
       [0.0841636 , 0.63128167, 0.94457049, 0.89123753, 0.87858258,
        0.34475163, 0.70310053, 0.5273376 ],
       [0.65931696, 0.26829063, 0.60776708, 0.04815737, 0.69550064,
        0.29927188, 0.16563555, 0.33225194],
       [0.16543775, 0.91463798, 0.28402501, 0.10760726, 0.11700177,
        0.7555236 , 0.83889446, 0.03553703]])

In [98]:
# Quick way to multiply ALL elements in this 2-D array by a constant (100)
randarray100 = randarray * 100
randarray100

array([[49.79400733, 67.94111176, 65.07859141, 26.87952387,  6.73246669,
        77.14451384, 48.09841323, 32.92064077],
       [51.06410562, 26.36288287, 31.051155  , 62.68534377, 55.74498106,
        31.85795596, 39.48432209, 25.79745859],
       [58.22411233, 16.16287104, 59.81338198, 82.58235773, 15.63917185,
        73.43005193, 40.86434321, 77.86879044],
       [80.39705676, 78.60714435, 59.22870187, 66.44892028, 64.65672868,
        42.5636479 , 51.35683338, 50.12578437],
       [ 3.70838109, 70.81160952, 62.04306002, 77.78085346, 45.94094656,
        37.98055547, 29.18922036, 55.72288625],
       [ 8.41636017, 63.12816691, 94.45704879, 89.12375349, 87.85825798,
        34.4751627 , 70.3100532 , 52.73376047],
       [65.93169556, 26.82906337, 60.77670794,  4.815737  , 69.55006394,
        29.92718777, 16.56355549, 33.22519401],
       [16.54377455, 91.4637981 , 28.40250059, 10.76072648, 11.70017702,
        75.55235988, 83.88944582,  3.55370267]])

## Pseudo random numbers are generated ... look into using a seed
seed(seed=None)


Reseed a legacy MT19937 BitGenerator
This is a convenience, legacy function.
The best practice is to not reseed a BitGenerator, rather to recreate a new one. This method is here for legacy reasons. This example demonstrates best practice.
>>> from numpy.random import MT19937
>>> from numpy.random import RandomState, SeedSequence
>>> rs = RandomState(MT19937(SeedSequence(123456789)))
### Later, you want to restart the stream
>>> rs = RandomState(MT19937(SeedSequence(987654321)))

In [99]:
np.random.seed()
randarray100

array([[49.79400733, 67.94111176, 65.07859141, 26.87952387,  6.73246669,
        77.14451384, 48.09841323, 32.92064077],
       [51.06410562, 26.36288287, 31.051155  , 62.68534377, 55.74498106,
        31.85795596, 39.48432209, 25.79745859],
       [58.22411233, 16.16287104, 59.81338198, 82.58235773, 15.63917185,
        73.43005193, 40.86434321, 77.86879044],
       [80.39705676, 78.60714435, 59.22870187, 66.44892028, 64.65672868,
        42.5636479 , 51.35683338, 50.12578437],
       [ 3.70838109, 70.81160952, 62.04306002, 77.78085346, 45.94094656,
        37.98055547, 29.18922036, 55.72288625],
       [ 8.41636017, 63.12816691, 94.45704879, 89.12375349, 87.85825798,
        34.4751627 , 70.3100532 , 52.73376047],
       [65.93169556, 26.82906337, 60.77670794,  4.815737  , 69.55006394,
        29.92718777, 16.56355549, 33.22519401],
       [16.54377455, 91.4637981 , 28.40250059, 10.76072648, 11.70017702,
        75.55235988, 83.88944582,  3.55370267]])

In [100]:
# Pseudo random numbers
np.random.seed(seed=20)
# These all appear as random but if you want reproducible random numbers for the sake of re-creating an issue for instance, you can use a seed()
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4


array([[3, 9, 4],
       [6, 7, 2],
       [0, 6, 8],
       [5, 3, 0],
       [6, 6, 0]])

In [101]:
#finding unique numbers in an array
unique_array = np.unique([1, 2, 3, 4, 5, 1, 1, 2, 2, 44])

In [102]:
# @hen displaying these, it's important to remember that 'unique' is different than 'not a duplicate' ... this takes all numbers and return 1 vale for each, regardless of how many of that particular value are found in the array
unique_array

array([ 1,  2,  3,  4,  5, 44])

In [103]:
# Now try unique with the random array of integers
unique_rand = np.unique(random_array_4)
unique_rand

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
random_array_4

array([[3, 9, 4],
       [6, 7, 2],
       [0, 6, 8],
       [5, 3, 0],
       [6, 6, 0]])

## 3. Viewing Arrays and Matrices

In [105]:
a1

array([1, 2, 3])

In [106]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [110]:
print(a3) # 2x3x3
a3.shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


(2, 3, 3)

In [115]:
print("Get all of the first elements")
print("****")
print(a1[0])
print("****")
print(a2[0])
print("****")
print(a3[0])
print("****")

Get all of the first elements
****
1
****
[1. 2. 3.]
****
[[1 2 3]
 [4 5 6]
 [7 8 9]]
****


In [116]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[9, 5, 7, 5, 2],
         [6, 9, 3, 3, 9],
         [0, 6, 2, 3, 1],
         [8, 0, 2, 7, 6]],

        [[6, 8, 2, 1, 3],
         [2, 6, 9, 4, 6],
         [4, 8, 6, 2, 3],
         [1, 5, 2, 1, 8]],

        [[2, 4, 4, 8, 6],
         [0, 3, 4, 0, 5],
         [6, 9, 7, 4, 0],
         [6, 1, 9, 6, 7]]],


       [[[9, 7, 6, 9, 8],
         [8, 2, 2, 1, 5],
         [2, 9, 7, 5, 5],
         [9, 6, 9, 9, 5]],

        [[2, 9, 6, 1, 8],
         [1, 0, 8, 5, 0],
         [6, 5, 4, 2, 9],
         [9, 4, 5, 3, 9]],

        [[7, 1, 2, 3, 6],
         [5, 4, 4, 1, 8],
         [7, 1, 9, 2, 3],
         [4, 4, 4, 9, 0]]]])

In [117]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [133]:
a4[1][0][2][4]

5

In [122]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [129]:
a3_split = a3[:2, :3, 2:3]

In [130]:
print(a3_split)

[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]]


## Manipulating and Comparing arrays