In [28]:
import numpy as np
from numpy import dtype

## Data Types and Attributes

In [29]:
a1 = np.array([1, 2, 3])
type(a1)

numpy.ndarray

![](IMG_3155.jpg)

In [30]:
# 2x3
a2 = np.array([[1, 2.0, 3.0],
       [4, 5, 6.5]])

# 3x3x2 n-dimensional array?
a3 = np.array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],
       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a1.shape

(3,)

In [34]:
a2.shape

(2, 3)

In [35]:
a3.shape

(2, 3, 3)

In [36]:
# show the dimensions of hte n-dim arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [37]:
# Look at the data types dtype
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [38]:
print(a2[1][1])

5.0


In [39]:
# Show Sizes (number of elements in each n-dim array)
a1.size, a2.size, a3.size

(3, 6, 18)

In [40]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a Data Frame (pandas) from a Numpy Array (numpy)

In [47]:
import pandas as pd
df = pd.DataFrame(a2)

In [48]:
df

0       1       2
0 1.00000 2.00000 3.00000
1 4.00000 5.00000 6.50000

In [51]:
df[2][1]

6.5

## Machine Learning is = finding patterns in Numpy Arrays

## Creating Arrays

In [5]:
import numpy as np
sample_array = np.array([1, 2, 3])
print("the type is: ")
type(sample_array)

the type is: 


numpy.ndarray

In [6]:
print("the data type is: ")
sample_array.dtype

the data type is: 


dtype('int32')

In [9]:
# 4x4 array filled with ones
ashape = (4, 4)
ones = np.ones(ashape)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
ones.dtype

dtype('float64')

In [11]:
type(ones)

numpy.ndarray

In [12]:
# 4x4 array filled with zeros
zeros = np.zeros(ashape)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Create array from 0 to 100 - noninclusive - and increment value 5 steps...
range_array = np.arange(0, 100, 5, dtype=int)
range_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [16]:
# Random Array with value ranging from 0 to 10 and make it 2-D per (ashape = (4, 4))
random_array = np.random.randint(0, 10, size=ashape)
random_array

array([[1, 0, 2, 3],
       [5, 4, 2, 1],
       [8, 4, 3, 3],
       [3, 8, 1, 1]])

In [17]:
# show size nd shape of hte ransom array
random_array.dtype

dtype('int32')

In [18]:
random_array.shape

(4, 4)

In [19]:
random_array.size

16

In [20]:
# random.random will return random floats between 0 and 1 ... I can multiply them all by 100
randarray = np.random.random((8, 8))
randarray

array([[0.64710436, 0.43969057, 0.15403073, 0.20764544, 0.82805147,
        0.96954247, 0.53888481, 0.02339202],
       [0.23113225, 0.51241217, 0.70277337, 0.51367115, 0.9109208 ,
        0.32206209, 0.41735122, 0.86224433],
       [0.9557684 , 0.87537874, 0.69147708, 0.69541492, 0.04351792,
        0.38340275, 0.19220591, 0.54700331],
       [0.33825021, 0.52136244, 0.30706777, 0.15449439, 0.19268935,
        0.63733707, 0.71555142, 0.9065946 ],
       [0.84700813, 0.25155885, 0.71782462, 0.73437085, 0.07514032,
        0.55997518, 0.34313174, 0.83797591],
       [0.55236187, 0.96648372, 0.05631159, 0.39158796, 0.88663604,
        0.66873878, 0.46412475, 0.76278919],
       [0.40040561, 0.51347932, 0.89135851, 0.43064746, 0.14074463,
        0.90934834, 0.03977139, 0.00178086],
       [0.72576293, 0.25410853, 0.26182423, 0.68837722, 0.3078024 ,
        0.07005148, 0.96867168, 0.70638351]])

In [21]:
# Quick way to multiply ALL elements in this 2-D array by a constant (100)
randarray100 = randarray * 100
randarray100

array([[64.71043557, 43.96905678, 15.40307258, 20.76454358, 82.80514739,
        96.95424699, 53.88848131,  2.33920236],
       [23.11322545, 51.24121721, 70.27733718, 51.36711466, 91.09208038,
        32.20620912, 41.73512163, 86.22443256],
       [95.57684046, 87.53787367, 69.1477078 , 69.54149177,  4.3517923 ,
        38.34027462, 19.22059077, 54.70033095],
       [33.82502082, 52.13624427, 30.70677668, 15.44943914, 19.26893543,
        63.73370694, 71.55514196, 90.65945968],
       [84.7008128 , 25.15588547, 71.78246243, 73.43708511,  7.51403211,
        55.99751814, 34.31317409, 83.79759073],
       [55.23618676, 96.64837185,  5.63115859, 39.15879601, 88.66360351,
        66.8738776 , 46.41247482, 76.27891902],
       [40.04056055, 51.34793245, 89.13585066, 43.06474594, 14.07446318,
        90.93483386,  3.97713853,  0.17808591],
       [72.57629327, 25.41085327, 26.18242328, 68.8377221 , 30.78024028,
         7.00514809, 96.86716773, 70.63835119]])

## Pseudo random numbers are generated ... look into using a seed
seed(seed=None)


Reseed a legacy MT19937 BitGenerator
This is a convenience, legacy function.
The best practice is to not reseed a BitGenerator, rather to recreate a new one. This method is here for legacy reasons. This example demonstrates best practice.
>>> from numpy.random import MT19937
>>> from numpy.random import RandomState, SeedSequence
>>> rs = RandomState(MT19937(SeedSequence(123456789)))
### Later, you want to restart the stream
>>> rs = RandomState(MT19937(SeedSequence(987654321)))

In [27]:
np.random.seed()
randarray100

array([[64.71043557, 43.96905678, 15.40307258, 20.76454358, 82.80514739,
        96.95424699, 53.88848131,  2.33920236],
       [23.11322545, 51.24121721, 70.27733718, 51.36711466, 91.09208038,
        32.20620912, 41.73512163, 86.22443256],
       [95.57684046, 87.53787367, 69.1477078 , 69.54149177,  4.3517923 ,
        38.34027462, 19.22059077, 54.70033095],
       [33.82502082, 52.13624427, 30.70677668, 15.44943914, 19.26893543,
        63.73370694, 71.55514196, 90.65945968],
       [84.7008128 , 25.15588547, 71.78246243, 73.43708511,  7.51403211,
        55.99751814, 34.31317409, 83.79759073],
       [55.23618676, 96.64837185,  5.63115859, 39.15879601, 88.66360351,
        66.8738776 , 46.41247482, 76.27891902],
       [40.04056055, 51.34793245, 89.13585066, 43.06474594, 14.07446318,
        90.93483386,  3.97713853,  0.17808591],
       [72.57629327, 25.41085327, 26.18242328, 68.8377221 , 30.78024028,
         7.00514809, 96.86716773, 70.63835119]])