![](SciKitLearnStructure.png)

###

### Intro to SciKit learn

In [51]:
from IPython.terminal.shortcuts.filters import pass_through

what_were_covering = [
    "0. And end-to-end Scikit-Learn Workflow",
    "1. Getting the Data Ready",
    "2. Choose the right estimator/algorithm for our problems",
    "3. Fit the model/algorithms and use it to make predictions on our data",
    "4. Evaluating the Model",
    "5. Improve the Model",
    "6. Save and load a trained model",
    "7. Putting it all together"
]

In [52]:
from Xlib.rdb import value_escape_re

#from mysample import car_sales
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import numpy as np

### 0. An end-to-end Scikit Learn Workflow

### 1. Get the Data ready

In [53]:
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [54]:
# Create X (Features Matrix)
X = heart_disease.drop("target", axis=1)

# Create y (Labels)
y = heart_disease["target"]

### 2.  Choose the right model and hyperparameters

In [55]:
# This is a 'classification' problem because we want to determine whether or not a person has heart disease

# This is a classification machine-learning model (RandomForest Classifier)
from sklearn.ensemble import RandomForestClassifier
# instantiate the class
clf = RandomForestClassifier()
# keep the default hyper parameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

### 3. Fit the model to the training data

In [56]:
from sklearn.model_selection import train_test_split
# test size is 20%, while 80% is used for training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [57]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [58]:
# Now we can make a prediction (still in step 3)
##### y_label = clf.predict(np.array([0, 2, 3, 4]))

In [59]:
# The y preditions needs to work on the X_test data set
y_preds = clf.predict(X_test)
y_preds

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1])

In [60]:
y_test

162    1
70     1
54     1
247    0
203    0
      ..
246    0
40     1
99     1
97     1
146    1
Name: target, Length: 61, dtype: int64

### 4. Evaluate the model on the training data and the test data

In [61]:
clf.score(X_train, y_train)


1.0

In [62]:
clf.score(X_test, y_test)

0.819672131147541

In [63]:
# Show some classification metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.74      0.93      0.83        28
           1       0.92      0.73      0.81        33

    accuracy                           0.82        61
   macro avg       0.83      0.83      0.82        61
weighted avg       0.84      0.82      0.82        61



In [64]:
confusion_matrix(y_test, y_preds)

array([[26,  2],
       [ 9, 24]])

In [65]:
accuracy_score(y_test, y_preds)

0.819672131147541

### 5. Improve a model

In [66]:
# Try different amount of n_estimators
np.random.seed(42)
for i in range(20, 100, 20):
    print(f"Trying model with {i} estimators ... ")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 20 estimators ... 
Model accuracy on test set: 80.33%

Trying model with 40 estimators ... 
Model accuracy on test set: 83.61%

Trying model with 60 estimators ... 
Model accuracy on test set: 83.61%

Trying model with 80 estimators ... 
Model accuracy on test set: 85.25%



### 6. Save a model and load it

In [67]:
import pickle
pickle.dump(clf, open('random_forest_model.pkl', 'wb'))

In [68]:
loaded_model = pickle.load(open('random_forest_model.pkl', 'rb'))

In [69]:
print(loaded_model.score(X_test, y_test))

0.8524590163934426


### ***** STARTING NEW SECTION *****

### Standard Imports

In [70]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
### import seaborn as sns

### 1. Getting our data ready to be used with machine learning
Three things we have to do:
   1. Split the data into feature and labels (usually 'X' & 'y') Feature,X ... Labels,y
   2. Filling (also called imputing) or disregarding missing values
   3. Converting non-numerical values to numerical values (also called feature encoding)

## Split the data into training and test data

In [71]:
#Import the heart_disease data set
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [72]:
# We want to use the feature columns to predict 'y'
# the feature columns are the age, sex, cp, trestbps, etc.
# the y is the target (whether patient has heart disease or not
X = heart_disease.drop("target", axis=1) # Axis 1 = the column headers so saying Axis 1-> target, will drop() the "target" item from the Axis column headers
# X is going to be every single column except for "target"
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [73]:
# y will now equal the target column
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [74]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split
# When we call this it will return 4 values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [75]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [76]:
# in the above the split took place - there are 303 total samples, and now the training data is split into 80/20
# since X = heart_disease with the target column dropped, it should contain the entire number of rows still...
print(X.shape)
# 303
print(X.shape[0] * 0.8)

(303, 13)
242.4


In [77]:
len(heart_disease)
# 303

303

### Let's make sure all the data is numerical

In [78]:
what_were_covering

['0. And end-to-end Scikit-Learn Workflow',
 '1. Getting the Data Ready',
 '2. Choose the right estimator/algorithm for our problems',
 '3. Fit the model/algorithms and use it to make predictions on our data',
 '4. Evaluating the Model',
 '5. Improve the Model',
 '6. Save and load a trained model',
 '7. Putting it all together']

In [79]:
# Import the Extended Car Sales Data for detailed analysis
car_sales = pd.read_csv("data/car-sales-extended.csv")
car_sales.head()


Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [80]:
len(car_sales)

1000

In [81]:
car_sales.dtypes
#car_sales.describe()

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [82]:
# On the outset we are going to use the 4 columns: Make, Color, Odometer, Doors... to predict the car's price.
# In terms of the objects like the car's color, will have to make those into numeric values ... will see how to make the strings into numbers.


In [83]:
# Split into X/y
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# We need to use the X values to predict the y values - doors, odometer, etc. to predict Price.

### Split into training and test set first

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [85]:
# Learn from X-train and y_train and then predict on the test data X_test, y_test
# Now, build a machine learning model:
from sklearn.ensemble import RandomForestRegressor
# in this case the 'regressor' will try to predict a number
# CREATE A MODEL
model = RandomForestRegressor()


In [86]:
# TRAIN IT
########## model.fit(X_train, y_train)
# Learning the patterns between the X variable and the Price


In [87]:
# And then we want to score it on the test data
# RUN IT
########## model.score(X_test, y_test)

### Now running this in the current state will fail because some of the data re not numbers, they are strings and strings are Objects... they need to be Integers.

## Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                   one_hot,
                                   categorical_features)],
                                   remainder = "passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [ ]:
r
