In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Numpy Data Types and attributes

In [38]:
# NumPy ndarray ... meaning n-dimensional array

In [39]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([
               [6, 7, 8, 9, 10],
               [11,12,13,14,15]
              ])
print(a1)
print(a2)
print(a1 + a2)
print(a1.dtype)
print(type(a2))

[1 2 3 4 5]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 7  9 11 13 15]
 [12 14 16 18 20]]
int64
<class 'numpy.ndarray'>


## Creating the (2,3,3) matrix

In [40]:
a3 = np.array([
                [[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]],
                [[13,14,15,],[16,17,18]]
              ])

In [41]:
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [42]:
print(a3[1][1][2])

12


In [43]:
a3.shape

(3, 2, 3)

In [44]:
a3.ndim

3

In [45]:
a3.size

18

In [46]:
type(a3)

numpy.ndarray

## Create a Data Frame from a NumPy Array

In [47]:
df = pd.DataFrame(a2)
df

0   1   2   3   4
0   6   7   8   9  10
1  11  12  13  14  15