# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
array1d = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
array2d = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
array3d = np.array([    [[1,2,3],
                        [4,5,6]],

                        [[7,8,9],
                        [10,11,12]],

                        [[13,14,15],
                         [16,17,18]]
                    ])
# Should equal 9
print(array3d[1,0,2])


9


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(array1d)
print(array1d.shape)
print(array1d.size)
print(array1d.dtype)
print(array1d.ndim)

[1 2 3 4 5]
(5,)
5
int32
1


In [6]:
# Attributes of 2-dimensional array
print(array2d)
print(array2d.shape)
print(array2d.size)
print(array2d.dtype)
print(array2d.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int32
2


In [7]:
# Attributes of 3-dimensional array
print(array3d)
print(array3d.shape)
print(array3d.size)
print(array3d.dtype)
print(array3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)
18
int32
3


In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
MyDataFrame = pd.DataFrame(array2d)
MyDataFrame

0  1  2
0  1  2  3
1  4  5  6

In [9]:
# Create an array of shape (10, 2) with only ones
ones_matrix = np.ones((10,2), dtype = int)
ones_matrix

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
ones3darray = np.zeros((7, 2, 3), dtype = int)
ones3darray

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
step3array = np.array(range(0,100,3))
# here we have beginning with, ending with, and number of steps between
step3array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randarray01072 = np.random.randint(0,10, size=(7,2))
randarray01072

array([[8, 9],
       [7, 0],
       [2, 3],
       [5, 2],
       [5, 4],
       [2, 5],
       [4, 7]])

In [13]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randarrayflt = np.random.rand(3,5)
randarrayflt

array([[0.46845478, 0.50996243, 0.33357572, 0.7519881 , 0.43504383],
       [0.99131468, 0.24440922, 0.56738653, 0.95697993, 0.13431249],
       [0.38980805, 0.23671694, 0.95723248, 0.61683994, 0.74272883]])

In [14]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
randarray4246 = np.random.randint(0,10, size=(4,6))
randarray4246

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [15]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randarray37 = np.random.randint(1,20, size=(3,7))
print(randarray37)

# Find the unique numbers in the array you just created
np.unique(randarray37)


[[12 17 10 16 15 15 19]
 [12  3  5 19  7  9  7]
 [18  4 14 18  9  2 15]]


array([ 2,  3,  4,  5,  7,  9, 10, 12, 14, 15, 16, 17, 18, 19])

In [16]:
# Find the 0'th index of the latest array you created
zeroindex = np.unique(randarray37[0][0])
print(zeroindex)

[12]


In [17]:
# Get the first 2 rows of latest array you created
row1 = (randarray37[0])
row2 = (randarray37[1])
print(row1)
print(row2)


[12 17 10 16 15 15 19]
[12  3  5 19  7  9  7]


In [18]:
# Get the first 2 values of the first 2 rows of the latest array
print(row1[0:2])
print(row2[0:2])

[12 17]
[12  3]


In [54]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
randarray_zero_ten = np.random.randint(0,10, size=(3,5))
array_of_ones = np.ones(shape=(3,5), dtype = int)


In [55]:
# Add the two arrays together
array_add_together = randarray_zero_ten + array_of_ones
print(array_add_together)

[[10  2 10  4  8]
 [ 7  9  8  5  2]
 [ 5  8 10  9  9]]


In [56]:
# Create another array of ones of shape (5, 3)
array_of_ones_53 = np.ones(shape=(5,3), dtype = int)

In [57]:
# Try add the array of ones and the other most recent array together
add_together = array_of_ones + array_of_ones_53
print(add_together)


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?
the shape is different
How would you fix it?
reshape one of the arrays

In [59]:
# Create another array of ones of shape (3, 5)
array_of_ones_3_5 = np.ones(shape=(3,5), dtype = int)


In [65]:
# Subtract the new array of ones from the other most recent array
subtract_array = array_add_together - array_of_ones_3_5
print(subtract_array)

[[9 1 9 3 7]
 [6 8 7 4 1]
 [4 7 9 8 8]]


In [66]:
# Multiply the ones array with the latest array
tem = subtract_array * array_of_ones_3_5
print(tem)

[[9 1 9 3 7]
 [6 8 7 4 1]
 [4 7 9 8 8]]


In [68]:
# Take the latest array to the power of 2 using '**'
squared_array = []
for number in tem:
    squared_array.append(number ** 2)
print(squared_array)

[array([81,  1, 81,  9, 49]), array([36, 64, 49, 16,  1]), array([16, 49, 81, 64, 64])]


In [69]:
# Do the same thing with np.square()
squared_array2 = np.square(tem)
print(squared_array2)


[[81  1 81  9 49]
 [36 64 49 16  1]
 [16 49 81 64 64]]


In [28]:
 # Find the mean of the latest array using np.mean()


In [29]:
# Find the maximum of the latest array using np.max()


In [30]:
# Find the minimum of the latest array using np.min()


In [31]:
# Find the standard deviation of the latest array


In [32]:
# Find the variance of the latest array


In [33]:
# Reshape the latest array to (3, 5, 1)


In [34]:
# Transpose the latest array


What does the transpose do?

In [35]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [36]:
# Perform a dot product on the two newest arrays you created


In [37]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [38]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [39]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [40]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [41]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [42]:
# Compare the two arrays with '>='


In [43]:
# Find which elements of the first array are greater than 7


In [44]:
# Which parts of each array are equal? (try using '==')


In [45]:
# Sort one of the arrays you just created in ascending order


In [46]:
# Sort the indexes of one of the arrays you just created


In [47]:
# Find the index with the maximum value in one of the arrays you've created


In [48]:
# Find the index with the minimum value in one of the arrays you've created


In [49]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [50]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [51]:
# Create an array of normally distributed random numbers


In [52]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.