In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame

## Numpy Data Types and attributes

In [68]:
# NumPy ndarray ... meaning n-dimensional array

In [69]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([
               [6, 7, 8, 9, 10],
               [11,12,13,14,15]
              ])
print(a1)
print(a2)
print(a1 + a2)
print(a1.dtype)
print(type(a2))

[1 2 3 4 5]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 7  9 11 13 15]
 [12 14 16 18 20]]
int64
<class 'numpy.ndarray'>


## Creating the (2,3,3) matrix

In [70]:
a3 = np.array([
                [[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]],
                [[13,14,15,],[16,17,18]]
              ])

In [71]:
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [72]:
print(a3[1][1][2])

12


In [73]:
a3.shape

(3, 2, 3)

In [74]:
a3.ndim

3

In [75]:
a3.size

18

In [76]:
type(a3)

numpy.ndarray

## Create a Data Frame from a NumPy Array

In [77]:
df = pd.DataFrame(a2)
df

0   1   2   3   4
0   6   7   8   9  10
1  11  12  13  14  15

In [78]:
# populate a numoy array with all 1's - Array is 2x3
ones = np.ones((2,3), dtype=int)
print(ones)

[[1 1 1]
 [1 1 1]]


In [79]:
# Ensure types is int
ones.dtype

dtype('int64')

In [80]:
# Create a pandas DataFrame and populate it with the np array
df = pd.DataFrame(ones)

In [81]:
# View the DataFrame
df

0  1  2
0  1  1  1
1  1  1  1

In [82]:
# What data types is the 'ones' array? - numpy.ndarray
type(ones)

numpy.ndarray