In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Numpy Data Types and attributes

In [7]:
# NumPy ndarray ... meaning n-dimensional array

In [9]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])
print(a1)
print(a2)
print(a1 + a2)
print(a1.dtype)
print(type(a2))

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
int64
<class 'numpy.ndarray'>


## Creating the (2,3,3) matrix

In [11]:
a3 = np.array([
                [[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]],
                [[13,14,15,],[16,17,18]]
              ])

In [12]:
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
